/**
 * Created by ruslan on 17.02.17.
 */

// edit panel
export const IS_ACTIVE_EDIT_PANEL = 'IS_ACTIVE_EDIT_PANEL';
export const CREATE_NODE_STYLES = 'CREATE_NODE_STYLES';
export const DELETE_NODE_STYLES = 'DELETE_NODE_STYLES';
export const CHANGE_BACKGROUND_COLOR = 'CHANGE_BACKGROUND_COLOR';
export const SELECT_EDIT_PANEL_NAVIGATION = 'SELECT_EDIT_PANEL_NAVIGATION';
export const TOGGLE_COLOR_PICKER = 'TOGGLE_COLOR_PICKER';
export const VALUE_IMAGE_LINK = 'VALUE_IMAGE_LINK';
export const VALUE_PADDING = 'VALUE_PADDING';
export const VALUE_MARGIN = 'VALUE_MARGIN';